import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";
import Image from "next/image";
import ReduxProvider from "@/components/layouts/reduxProvider";
import ModalProvider from "@/components/layouts/modalCommon/modalProvider";
import ToastifyProvider from "@/components/layouts/toastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header />
          <div className="bg-[#f9f9f9]">
            <div className="relative h-[150px]">
              <Image
                src="/banner-top.png"
                alt="banner top"
                fill
                className="object-cover"
              />
            </div>
            {children}
          </div>
          <ModalProvider />
        </ReduxProvider>
        <ToastifyProvider />
      </body>
    </html>
  );
}
